# The schedule event allows you to trigger a workflow at a scheduled time.
# You can schedule a workflow to run at specific UTC times using POSIX cron syntax.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.guru/#0_4_1_*_*
    - cron:  '0 4 1 * *'

jobs:
  scrape_tjv_dataset:
    runs-on: ubuntu-latest
    name: Scrape tjv snapshot to repo
    steps:
      # This is required to use the git-auto-commit-action
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Load current date
      # https://github.com/marketplace/actions/current-time
      # alt: https://github.com/marketplace/actions/current-time-2
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      # Display current time
      #- name: Use current time
      #  env:
      #    TIME: "${{ steps.current-time.outputs.time }}"
      #  run: echo $TIME

      # Load and cache the image
      - name: Fetch tjv csv snapshot
        uses: Minituff/save-image@v1.3
        id: wakatime
        with:
          url: 'http://tjv.pristupinfo.hr/?sort=1&page=1&download'
          imagePath: 'tijela_javne_vlasti/tjv-snapshot-${{ steps.current-time.outputs.time }}.csv'
          #requiredContentType: 'text/csv'

      # If you do not commit the changes, then the action does not work
      - name: "Commit tjv csv snapshot"
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Adding tjv csv snapshot
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: Author <github-actions[bot]@users.noreply.github.com>

    update_tjv_image:
      runs-on: ubuntu-latest
      name: Update main tjv dataset in repo
      steps:
        # This is required to use the git-auto-commit-action
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}

        # Load current date
        # https://github.com/marketplace/actions/current-time
        # alt: https://github.com/marketplace/actions/current-time-2
        - name: Get current time
          uses: gerred/actions/current-time@master
          id: current-time

        # Display current time
        #- name: Use current time
        #  env:
        #    TIME: "${{ steps.current-time.outputs.time }}"
        #  run: echo $TIME

        # Load and cache the image
        - name: Fetch tjv csv dataset
          uses: Minituff/save-image@v1.3
          id: wakatime
          with:
            url: 'http://tjv.pristupinfo.hr/?sort=1&page=1&download'
            imagePath: 'tijela_javne_vlasti/tjv-main-dataset.csv'
            #requiredContentType: 'text/csv'

        # If you do not commit the changes, then the action does not work
        - name: "Commit updated changes in tjv image"
          uses: stefanzweifel/git-auto-commit-action@v4.13.1
          with:
            commit_message: Updating tjv image
            commit_user_name: github-actions[bot]
            commit_user_email: github-actions[bot]@users.noreply.github.com
            commit_author: Author <github-actions[bot]@users.noreply.github.com>
